type: one_to_one
engine_key: households_useful_demand_heat_per_person
display: slider
min: 18
max: 23
start: 20
step: 0.5
unit: degrees
formula: >
  3.0 + (-1.0 + (1.0 + 0.079718 * (comfort_temperature_in_the_house - 20.0))**0.05) * 100
