type: one_to_one
engine_key: households_useful_demand_for_cooling
display: radio
start: no_cooling
options:
  -
    key: no_cooling
    effects:
      households_useful_demand_for_cooling: -5

  -
    key: one_room_cooling
    effects:
      households_useful_demand_for_cooling: 4

  -
    key: whole_house_cooling
    effects:
      households_useful_demand_for_cooling: 10
