version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
    environment:
      - DATABASE_HOST=database
      - MYSQL_DATABASE=etflex_development
      - MYSQL_PASSWORD=dev
      - MYSQL_USER=root
    tmpfs:
      - /tmp
    depends_on:
      - database

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=etflex_development
    volumes:
      - db_data:/var/lib/mysql

volumes:
  bundle:
  db_data:
  rails_cache:
