---
production: &production

  # The base API for all API requests. Include the protocol and path to the
  # API endpoint.
  api_url: 'https://engine.energytransitionmodel.com'

  # Set the Pusher credentials with which to send and receive updates. Set to
  # false to disable real-time updates.
  #
  # pusher:
  #   app_id: something
  #   key:    something
  #   secret: something
  pusher:
    key: <%= ENV.fetch('PUSHER_APP_ID', false) %>
    key: <%= ENV.fetch('PUSHER_KEY', '') %>
    secret: <%= ENV.fetch('PUSHER_SECRET', '') %>

  # Enable when displaying ETFlex in public settings. This will change the
  # root page behaviour so that the BIG button always creates a totally new
  # session and demotes "Continue..." to a smaller link.
  conference: false

  # A list of browsers which are supported by ETFlex. Browsers not in this
 # list  will still be permitted to use the site, but are displayed a message
  # on first load, and then have a small banner at the top of each page.
  supported_browsers:
    - ie9
    - ie8
    - ie10
    - chrome
    - firefox
    - safari
    - ipad
    - opera

  # offline laptops disable CORS
  offline: false

  # Base URL of the ETM (used to open the current scenario). Only laptops need
  # to set this value. If blank or missing the JS app will use the live server
  # (or beta) as default
  etm_url: false

staging:     *production
development: *production

test: &test
  <<: *production

  # Assume puma-dev is present for testing.
  api_url: <%= ENV.fetch('API_URL', 'http://localhost:3000') %>

  # Always default conference mode off.
  conference: false
