# DO NOT MODIFY BENEATH THIS LINE.
#
# The "props" map is automatically generated by running the rake task
# "etflex:generate_prop_map"; any changes made below will be erased next time
# the task is run.
#
# Instead, change config/prop_map.yml.
module.exports =
  'co2-emissions': { path: 'co2_emissions', klass: 'CO2EmissionsView' }
  'score': { path: 'score', klass: 'ScoreView' }
  'reliability': { path: 'reliability', klass: 'ReliabilityView' }
  'costs': { path: 'costs', klass: 'CostsView' }
  'icon': { path: 'icon', klass: 'IconProp' }
  'renewables': { path: 'renewables', klass: 'RenewablesView' }
  'supply-demand': { path: 'supply_demand', klass: 'SupplyDemandView' }
  'investment': { path: 'investment', klass: 'InvestmentView' }
  'energy-bill': { path: 'energy_bill', klass: 'EnergyBillView' }
  'car': { path: 'headers/car', klass: 'CarProp' }
  'city': { path: 'headers/city', klass: 'CityProp' }
  'eco-buildings': { path: 'headers/eco_buildings', klass: 'EcoBuildingsProp' }
  'energy-sources': { path: 'headers/energy_sources', klass: 'EnergySourcesProp' }
  'geothermal-pipeline': { path: 'headers/geothermal_pipeline', klass: 'GeothermalPipelineProp' }
  'ground': { path: 'headers/ground', klass: 'GroundProp' }
  'solar-heater': { path: 'headers/solar_heater', klass: 'SolarHeaterProp' }
  'turbines': { path: 'headers/turbines', klass: 'TurbinesProp' }
